/* tslint:disable */
/* eslint-disable */
/* auto-generated by NAPI-RS */
/* Customized loader for @typedb/embedded-node */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

/**
 * Mapping of Node.js platform/arch to napi-rs target triple suffixes
 */
function getBindingName() {
  switch (platform) {
    case 'darwin':
      switch (arch) {
        case 'x64':
          return 'typedb-node.darwin-x64.node'
        case 'arm64':
          return 'typedb-node.darwin-arm64.node'
        default:
          throw new Error(`Unsupported architecture on macOS: ${arch}`)
      }
    case 'linux':
      switch (arch) {
        case 'x64':
          // Check for musl vs glibc
          if (isMusl()) {
            throw new Error('Linux musl is not yet supported. Please use glibc-based Linux.')
          }
          return 'typedb-node.linux-x64-gnu.node'
        case 'arm64':
          if (isMusl()) {
            throw new Error('Linux musl is not yet supported. Please use glibc-based Linux.')
          }
          return 'typedb-node.linux-arm64-gnu.node'
        default:
          throw new Error(`Unsupported architecture on Linux: ${arch}`)
      }
    case 'win32':
      switch (arch) {
        case 'x64':
          return 'typedb-node.win32-x64-msvc.node'
        default:
          throw new Error(`Unsupported architecture on Windows: ${arch}`)
      }
    default:
      throw new Error(`Unsupported platform: ${platform}`)
  }
}

/**
 * Detect musl libc on Linux.
 * Returns false on any error (assumes glibc if detection fails).
 * This is intentional - glibc is more common, and musl users
 * will get a clear "not supported" error from getBindingName().
 */
function isMusl() {
  // Check for Alpine Linux
  if (existsSync('/etc/alpine-release')) {
    return true
  }
  // Check ldd version output for musl
  try {
    const { execSync } = require('child_process')
    const lddOutput = execSync('ldd --version 2>&1', { encoding: 'utf8' })
    return lddOutput.includes('musl')
  } catch {
    // If ldd fails, assume glibc (more common)
    return false
  }
}

const bindingName = getBindingName()
const localPath = join(__dirname, bindingName)

if (existsSync(localPath)) {
  localFileExisted = true
  try {
    nativeBinding = require(localPath)
  } catch (e) {
    loadError = e
  }
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }

  const message = localFileExisted
    ? `Failed to load native binding: ${localPath}`
    : `Native binding not found: ${localPath}\n\nSupported platforms:\n` +
      `  - macOS x64 (darwin-x64)\n` +
      `  - macOS arm64 (darwin-arm64)\n` +
      `  - Linux x64 glibc (linux-x64-gnu)\n` +
      `  - Linux arm64 glibc (linux-arm64-gnu)\n` +
      `  - Windows x64 (win32-x64-msvc)\n\n` +
      `Current platform: ${platform}-${arch}`

  throw new Error(message)
}

module.exports.Database = nativeBinding.Database
module.exports.TransactionRead = nativeBinding.TransactionRead
module.exports.TransactionWrite = nativeBinding.TransactionWrite
module.exports.TransactionSchema = nativeBinding.TransactionSchema
module.exports.enableProfiling = nativeBinding.enableProfiling
module.exports.takeProfile = nativeBinding.takeProfile
